### ISSUE TITLE
Q question: why would I want to use this?

### ISSUE THREAD

**Issue by rahamin1** [EvanBacon/expo-native-firebase#7]
_Tried to write a comment in the medium article of Oct 4th, but failed. That's why I am asking this here._

The understanding of a novice (myself) is the following:

- I wouldn't like to create a detached project, since I will lose important advantages of working within expo (creating an apk/ipa is one that is extremely important to me) 
- If I want to use this package I need to detach
- I can use firebase with expo without detaching, as explained in in the expo docs.

So why would I want to use this package? is it only for reducing the app's size? Or for being able to use functionality that I cannot use without detaching?

**Comment by EvanBacon** [comment]
I will be putting out a video explaining more, essentially this adds native Firebase functionality. Because of reasons beyond my comprehension, google only allows certain features in the native API (like analytics 🙃). 
We are working on adding these modules to Expo but it will take some time. While we work on that, you could use this if you want to use all of these extra features. 
I like using the WebSDK in a normal Expo but these native capabilities are a highly requested feature. 
We are also working on ways to make generating APK/IPA simpler in an ejected project.

**Comment by rahamin1** [comment]
Thanks much for clarifying!
